apiVersion: v1
kind: Service
metadata:
  name: hstk-web
  labels:
    app: hstk-web
spec:
  selector:
    app: hstk-web
    role: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: hstk-web-db
  labels:
    app: hstk-web
spec:
  type: ClusterIP
  selector:
    app: hstk-web
    role: db
  ports:
    - name: sql
      port: 5432
      targetPort: 5432
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hstk-web
  labels:
    app: hstk-web
    role: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hstk-web
      role: web
  template:
    metadata:
      labels:
        app: hstk-web
        role: web
    spec:
      containers:
        - name: web
          image: gcr.io/carbon-sunup-250522/delvit/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: env
              mountPath: /app/.env
              subPath: .env

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hstk-web-db
  labels:
    app: hstk-web
    role: db
spec:
  serviceName: "hstk-web-db"
  selector:
    matchLabels:
      app: hstk-web
      role: db
  template:
    metadata:
      labels:
        app: hstk-web
        role: db
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hstk-web-db

      containers:
        - name: db
          image: postgres:15
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: data
          env:
            - name: POSTGRES_PASSWORD
              value: hstkPWD
